### ISSUE TITLE
Move to FSharp.Compiler.Service

### ISSUE THREAD

**Issue by ghost** [BayardRock/FSharpWebIntellisense#4]
Hi @Rickasaurus, @prosconi, @pblasucci,

Can you move this to use FSharp.Compiler.Service? http://fsharp.github.io/FSharp.Compiler.Service/

If not, let's work out why.

thanks
don

**Comment by prosconi** [comment]
Switched over, much cleaner now.

**Comment by ghost** [comment]
Awesome!
