### ISSUE TITLE
ACE editor does not work out-of-the-box

### ISSUE THREAD

**Issue by tpetricek** [BayardRock/FSharpWebIntellisense#7]
I just started playing with this (really nice work, thanks for making this!) and the CodeMirror demo works fine, but the ACE demo does not seem to work on my machine...

The first error I got was in `ext-intellisense.js` (line 139):

```
self.methodsElement.appendChild(self.arrowsElement);
```

In IE it says "Error: Unable to get property 'appendChild' of undefined or null reference." (and Chrome gives a similar error). Apparently, `self.methodsElement` is `null`. I tried fixing this by adding:

```
self.methodsElement = document.createElement('div');
```

But then I get another error on line 143 when adding the elements to the body:

```
document.body.appendChild(self.listElement);
document.body.appendChild(self.documentationElement);
document.body.appendChild(self.methodsElement);
```

IE gives a mysterious "Error: HierarchyRequestError", but it turns out that the other two are `null` too. So I tried creating these:

```
self.listElement = document.createElement('div');
self.documentationElement = document.createElement('div');
```

After these changes, it actually does something, but I always get intellisense for the top-level namespace. Is this expected or am I missing something?

**Comment by prosconi** [comment]
Fixed.
